import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#006c49",
        "primary-container": "#10b981",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        "on-primary-container": "#00422b",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#4edea3",
        "secondary": "#376850",
        "secondary-container": "#b7ebce",
        "secondary-fixed": "#baeed1",
        "secondary-fixed-dim": "#9ed2b5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3c6c54",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#1e4f3a",
        "tertiary": "#a43a3a",
        "tertiary-container": "#fc7c78",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#711419",
        "on-tertiary-fixed": "#410005",
        "on-tertiary-fixed-variant": "#842225",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "surface": "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-variant": "#d9e3f6",
        "surface-tint": "#006c49",
        "on-surface": "#121c2a",
        "on-surface-variant": "#3c4a42",
        "outline": "#6c7a71",
        "outline-variant": "#bbcabf",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
      },
      fontFamily: {
        headline: ["var(--font-lexend)", "Lexend", "sans-serif"],
        body: ["var(--font-public-sans)", "Public Sans", "sans-serif"],
        label: ["var(--font-public-sans)", "Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
